Document: webkitimageqt
Title: Debian webkitimageqt Manual
Author: <insert document author here>
Abstract: This manual describes what webkitimageqt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webkitimageqt/webkitimageqt.sgml.gz

Format: postscript
Files: /usr/share/doc/webkitimageqt/webkitimageqt.ps.gz

Format: text
Files: /usr/share/doc/webkitimageqt/webkitimageqt.text.gz

Format: HTML
Index: /usr/share/doc/webkitimageqt/html/index.html
Files: /usr/share/doc/webkitimageqt/html/*.html


